using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ForzaMotorsport
{
    static class Tracks
    {
        public static readonly Dictionary<int, string> TrackList = new Dictionary<int, string>
        {
            {0, "WeatherTech Raceway Laguna Seca Full Circuit"},
            {1, "WeatherTech Raceway Laguna Seca Short Circuit"},
            {3, "Road America Full Circuit"},
            {5, "Road America East Route"},
            {21, "Silverstone Racing Circuit Grand Prix Circuit"},
            {22, "Silverstone Racing Circuit National Circuit"},
            {23, "Silverstone Racing Circuit International Circuit"},
            {31, "Nürburgring Full Circuit"},
            {32, "Nürburgring Nordschleife"},
            {33, "Nürburgring GP Circuit"},
            {34, "Nürburgring Sprint Circuit"},
            {35, "Mugello Circuit Full Circuit"},
            {36, "Mugello Circuit Club Circuit"},
            {37, "Suzuka Circuit Full Circuit"},
            {38, "Suzuka Circuit East Circuit"},
            {40, "Sebring International Full"},
            {42, "Sebring International Short"},
            {67, "Maple Valley Full Circuit"},
            {68, "Maple Valley Short Circuit"},
            {70, "Maple Valley Short Circuit Reverse"},
            {100, "Le Mans - Circuit International de la Sarthe Full Circuit"},
            {101, "Le Mans - Circuit International de la Sarthe Old Mulsanne Circuit"},
            {110, "Circuit de Barcelona-Catalunya Grand Prix Circuit"},
            {111, "Circuit de Barcelona-Catalunya National Circuit"},
            {113, "Circuit de Barcelona-Catalunya National Circuit Alt"},
            {231, "Indianapolis Motor Speedway The Brickyard Speedway"},
            {232, "Indianapolis Motor Speedway Grand Prix Circuit"},
            {250, "Hockenheimring Full Circuit"},
            {251, "Hockenheimring National Circuit"},
            {252, "Hockenheimring Short Circuit"},
            {510, "Yas Marina Circuit Full Circuit"},
            {511, "Yas Marina Circuit North Circuit"},
            {512, "Yas Marina Circuit South Circuit"},
            {513, "Yas Marina Circuit North Corkscrew"},
            {530, "Circuit de Spa-Francorchamps Full Circuit"},
            {840, "Daytona Intl Speedway Sports Car Circuit"},
            {841, "Daytona Intl Speedway Tri-Oval Circuit"},
            {860, "Brand Hatch Tor Grand Prix"},
            {861, "Brand Hatch Tor Indy"},
            {870, "Watkins Glen International Speedway Full Circuit"},
            {873, "Watkins Glen International Speedway Short Circuit"},
            {880, "Lime Rock Park Full Circuit"},
            {882, "Lime Rock Park South Chicane"},
            {883, "Lime Rock Park Full Circuit Alt"},
            {990, "Virginia International Raceway Full"},
            {991, "Virginia International Raceway North"},
            {992, "Virginia International Raceway South"},
            {995, "Virginia International Raceway Grand West"},
            {996, "Virginia International Raceway Grand East"},
            {1110, "Homestead-Miami Speedway Speedway Circuit"},
            {1111, "Homestead-Miami Speedway Road Circuit"},
            {1450, "Mid-Ohio Sports Car Course Full Circuit"},
            {1452, "Mid-Ohio Sports Car Course Short Circuit"},
            {1590, "Kyalami Grand Prix Circuit Grand Prix Circuit"},
            {1630, "Grand Oak Raceway National Circuit"},
            {1631, "Grand Oak Raceway Club Circuit"},
            {1632, "Grand Oak Raceway National Circuit Reverse"},
            {1640, "Hakone Grand Prix Circuit"},
            {1641, "Hakone Club Circuit"},
            {1642, "Hakone Club Circuit Reverse"},
            {1660, "Eaglerock Speedway Oval Circuit"},
            {1661, "Eaglerock Speedway Club Circuit"},
            {1663, "Eaglerock Speedway Club Circuit Reverse"},
        };

        public static readonly Dictionary<int, float> TrackLength = new Dictionary<int, float>
        {
            {0, 3.6f},
            {1, 2.96f},
            {3, 6.52f},
            {5, 3.52f},
            {21, 5.89f},
            {22, 2.64f},
            {23, 2.98f},
            {31, 25.38f},
            {32, 20.83f},
            {33, 5.15f},
            {34, 3.63f},
            {35, 5.25f},
            {36, 2.58f},
            {37, 5.81f},
            {38, 2.25f},
            {40, 6.02f},
            {42, 3.54f},
            {67, 4.81f},
            {68, 1.85f},
            {70, 1.85f},
            {100, 13.63f},
            {101, 13.54f},
            {110, 4.66f},
            {111, 3.07f},
            {113, 3f},
            {231, 4.02f},
            {232, 3.93f},
            {250, 4.57f},
            {251, 3.69f},
            {252, 2.64f},
            {510, 5.28f},
            {511, 3f},
            {512, 2.19f},
            {513, 2.29f},
            {530, 7f},
            {840, 5.78f},
            {841, 4.02f},
            {860, 3.7f},
            {861, 1.93f},
            {870, 5.55f},
            {873, 3.94f},
            {880, 2.41f},
            {882, 2.37f},
            {883, 2.41f},
            {990, 5.26f},
            {991, 3.62f},
            {992, 2.66f},
            {995, 6.6f},
            {996, 6.76f},
            {1110, 2.41f},
            {1111, 3.56f},
            {1450, 3.62f},
            {1452, 2.82f},
            {1590, 4.53f},
            {1630, 3.73f},
            {1631, 2.62f},
            {1632, 3.73f},
            {1640, 4.28f},
            {1641, 3.32f},
            {1642, 3.32f},
            {1660, 1.64f},
            {1661, 1.72f},
            {1663, 1.72f},
        };
    }
}
